# fly.toml file generated for jira-clone on 2023-01-13T19:03:42+01:00

app = "jira-clone"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
DATABASE_URL = "file:/data/jira_clone.db"
PORT = "8080"

[mounts]
destination = "/data"
source = "data"

[[statics]]
guest_path = "/app/public/images"
url_prefix = "/static/images"

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
tcp_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80
http_options = { response = { headers = { Expect-CT = false } } }

[[services.ports]]
handlers = ["tls", "http"]
port = 443
